spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - www.abc.com
  - www.xyz.com
---
spring:
  config:
    activate:
      on-profile: dev
name: dev-YAML
environment: development
enable: false
servers:
  - www.abc.dev.com
  - www.xyz.dev.com
